"""Automated 40-band edge profiling, flank sidebearings, and band-gap kerning engine."""
from typing import Dict, List, Tuple, Any, Optional

BANDS = 40        # Horizontal slices from descender to ascender
LIMIT = 12        # Drop minor adjustments smaller than this
MAXNEG = -300     # Maximum tuck
MAXPOS = 150      # Maximum push apart
TUCK = 0.50       # Never tuck past 50% of preceding glyph advance
MIN_TIGHT = 52    # Closest ink may come before collision
MAX_TIGHT = 200   # Widest closest approach before it reads as a visual hole
AREA = 62         # Target average clear space on each flank
FLANK_FLOOR = 10  # Minimum sidebearing floor


def _densify_contour(contour: List[Tuple[float, float]], step: float = 12.0) -> List[Tuple[float, float]]:
    out = []
    n = len(contour)
    for i in range(n):
        x0, y0 = contour[i]
        x1, y1 = contour[(i + 1) % n]
        d = max(abs(x1 - x0), abs(y1 - y0))
        k = max(1, int(d / step))
        for t in range(k):
            out.append((x0 + (x1 - x0) * t / k, y0 + (y1 - y0) * t / k))
    return out


def compute_edge_profile(
    contours: List[List[Tuple[float, float]]],
    advance: float,
    descender: float = -220,
    ascender: float = 800,
    shift: float = 0.0
) -> Dict[str, Any]:
    """Slice glyph into 40 horizontal bands and record leftmost and rightmost ink."""
    bands = [None] * BANDS
    span = (ascender - descender) / float(BANDS)

    for c in contours:
        for x, y in _densify_contour(c):
            i = int((y - descender) / span)
            if 0 <= i < BANDS:
                x_shifted = x + shift
                b = bands[i]
                bands[i] = (x_shifted, x_shifted) if b is None else (min(b[0], x_shifted), max(b[1], x_shifted))

    return {
        "bands": bands,
        "adv": advance,
        "ink": sum(1 for b in bands if b is not None)
    }


def compute_flanks(
    bands: List[Optional[Tuple[float, float]]],
    descender: float = -220,
    ascender: float = 800,
    zone: Tuple[float, float] = (0, 437),
    target_area: float = AREA,
    floor: float = FLANK_FLOOR
) -> Tuple[float, float]:
    """Derive Left and Right Sidebearings (LSB, RSB) from glyph silhouette."""
    span = (ascender - descender) / float(len(bands))
    zl, zh = zone
    idx = [
        i for i, b in enumerate(bands)
        if b is not None and zl <= descender + (i + 0.5) * span <= zh
    ]
    if not idx:
        idx = [i for i, b in enumerate(bands) if b is not None]
    if not idx:
        return floor, floor

    ink = [bands[i] for i in idx]
    x0 = min(b[0] for b in bands if b is not None)
    x1 = max(b[1] for b in bands if b is not None)

    left_inset = sum(b[0] - x0 for b in ink) / len(ink)
    right_inset = sum(x1 - b[1] for b in ink) / len(ink)

    lsb = max(floor, target_area - left_inset)
    rsb = max(floor, target_area - right_inset)
    return lsb, rsb


def compute_kern_pairs(
    profiles: Dict[str, Dict[str, Any]],
    limit: int = LIMIT
) -> Dict[Tuple[str, str], int]:
    """Calculate kerning adjustments across all ordered pairs from closest band approach."""
    gaps = {}
    names = sorted(profiles)

    for a in names:
        pa = profiles[a]
        for b in names:
            pb = profiles[b]
            gap = None
            for ba, bb in zip(pa["bands"], pb["bands"]):
                if ba is None or bb is None:
                    continue
                g = (pa["adv"] - ba[1]) + bb[0]
                gap = g if gap is None else min(gap, g)

            if gap is None:
                continue

            shared = sum(1 for ba, bb in zip(pa["bands"], pb["bands"]) if ba is not None and bb is not None)
            tall = max(pa["ink"], pb["ink"])
            gaps[(a, b)] = (gap, shared / float(tall) if tall else 0.0)

    kerns = {}
    for (a, b), (gap, frac) in gaps.items():
        if gap < MIN_TIGHT:
            # Collision prevention
            v = MIN_TIGHT - gap
        elif gap > MAX_TIGHT:
            # Hole closure, attenuated by shared vertical overlap
            v = frac * (MAX_TIGHT - gap)
        else:
            continue

        v = int(round(max(v, -TUCK * profiles[a]["adv"])))
        if abs(v) < limit:
            continue

        kerns[(a, b)] = max(MAXNEG, min(MAXPOS, v))

    return kerns


def generate_fea(kerns: Dict[Tuple[str, str], int], path: str) -> str:
    """Write an OpenType Feature file for kern lookup."""
    with open(path, "w", encoding="utf-8") as f:
        f.write("# generated by graphicnovelsans kern engine\n")
        f.write("feature kern {\n")
        for (a, b), v in sorted(kerns.items()):
            f.write(f"    pos {a} {b} {v};\n")
        f.write("} kern;\n")
    return path


def create_legacy_kern_table(kerns: Dict[Tuple[str, str], int], glyph_order: set, cap: int = 10920) -> Any:
    """Build a format-0 legacy binary 'kern' table for older applications."""
    from fontTools.ttLib import newTable
    from fontTools.ttLib.tables import _k_e_r_n as K

    keep = kerns
    if len(keep) > cap:
        top = sorted(keep.items(), key=lambda kv: -abs(kv[1]))[:cap]
        keep = dict(top)

    st = K.KernTable_format_0(apple=False)
    st.format = 0
    st.version = 0
    st.coverage = 1
    st.tupleIndex = None
    st.kernTable = {
        k: v for k, v in keep.items()
        if k[0] in glyph_order and k[1] in glyph_order
    }

    t = newTable("kern")
    t.version = 0
    t.kernTables = [st]
    return t, len(st.kernTable)
